'use client';
import React,{useMemo,useState} from 'react';
import {DayPicker,DateRange} from 'react-day-picker';
import * as Popover from '@radix-ui/react-popover';
import {CalendarDays,ChevronRight,Clock3,MapPin,Search,Users} from 'lucide-react';
import 'react-day-picker/style.css';
import './calendar-crm-workspace.css';
const places=[{name:'Hawthorne Works',city:'Brooklyn',x:20,y:35,score:86},{name:'Northstar Lab',city:'Queens',x:68,y:28,score:72},{name:'Aperture Co.',city:'Manhattan',x:47,y:52,score:94},{name:'Field Office',city:'Jersey City',x:28,y:73,score:63},{name:'Parallel',city:'Bronx',x:58,y:14,score:81}];
const slots=['09:00','09:30','10:00','10:30','11:00','11:30','13:00','13:30','14:00'];
export function CalendarCRMWorkspace(){const [range,setRange]=useState<DateRange|undefined>();const [active,setActive]=useState(2);const [slot,setSlot]=useState('10:30');const days=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return d}),[]);return <main className="oc-page"><aside><div className="oc-brand">OPEN / FIELD</div><label><Search size={14}/><input placeholder="Search accounts"/></label><nav><b>Workspace</b><button className="on"><MapPin/> Territory</button><button><CalendarDays/> Calendar</button><button><Users/> Accounts</button></nav><div className="oc-list"><small>HIGH INTENT NEARBY</small>{places.map((p,i)=><button key={p.name} onClick={()=>setActive(i)} className={active===i?'on':''}><span><b>{p.name}</b><small>{p.city}</small></span><i>{p.score}</i></button>)}</div></aside><section className="oc-main"><header><div><small>TERRITORY / NYC</small><h1>Plan the week around live accounts.</h1></div><Popover.Root><Popover.Trigger asChild><button className="date-button"><CalendarDays size={15}/>{range?.from?range.from.toLocaleDateString():'Choose dates'}</button></Popover.Trigger><Popover.Portal><Popover.Content className="oc-pop" sideOffset={8}><DayPicker mode="range" selected={range} onSelect={setRange}/></Popover.Content></Popover.Portal></Popover.Root></header><div className="oc-week">{days.map((d,i)=><button key={i} className={i===active?'on':''} onClick={()=>setActive(i)}><small>{d.toLocaleDateString('en',{weekday:'short'})}</small><b>{d.getDate()}</b><span>{i===3?'FULL':i===5?'OFF':'3 OPEN'}</span></button>)}</div><div className="oc-content"><article className="oc-map"><div className="map-grid"/><div className="river"/>{places.map((p,i)=><button key={p.name} onClick={()=>setActive(i)} className={'pin '+(i===active?'active':'')} style={{left:p.x+'%',top:p.y+'%'}}><MapPin/><span>{p.name}</span></button>)}<div className="map-key"><span><i/> Account</span><span><i/> Selected</span></div></article><article className="oc-book"><small>BOOKING FLOW</small><h2>{places[active].name}</h2><p><MapPin size={13}/>{places[active].city} · intent {places[active].score}</p><div className="oc-slots">{slots.map((s,i)=><button key={s} disabled={i===2||i===6} onClick={()=>setSlot(s)} className={slot===s?'on':''}>{s}</button>)}</div><button className="oc-confirm"><span><Clock3/> {slot} · 30 min</span><ChevronRight/></button></article></div></section></main>}
