'use client';
import{useState}from'react';
import{Activity,ArrowRight,Box,CheckCircle2,ChevronDown,Clock3,Code2,GitBranch,GitPullRequest,Home,MessageSquare,MoreHorizontal,Play,Plus,Search,Settings,ShieldCheck,Sparkles,Terminal,Users,Workflow}from'lucide-react';
import'./tembo.css';
const sessions=[['Review pull requests to identify bugs, security issues and code quality problems','Running','monorepo','1 min ago'],['Generate a description whenever a new pull request is opened','Running','monorepo','3 mins ago'],['Design and Construct a Spaceship Prototype','Needs review','monorepo','4 mins ago'],['Add retry logic to the webhook dispatcher','Complete','api','1 hr ago']];
const templates=[['Auto Fix Sentry Errors','Diagnoses new Sentry errors, finds the root cause, and opens a fix PR.'],['Enrich Linear Issue','Adds context and implementation suggestions to new Linear issues.'],['Daily Slack Changelog','Summarizes daily code changes and posts a formatted changelog to Slack.']];
export function TemboProduct(){const[view,setView]=useState('Home');const[query,setQuery]=useState('');const[run,setRun]=useState(false);return <main className="tp-app"><aside><header>✣ <b>Tembo</b><button><Plus/></button></header>{[['Home',Home],['Sessions',MessageSquare],['Agents',Sparkles],['Reviews',GitPullRequest]].map(([x,I])=><button onClick={()=>setView(x as string)} className={view===x?'on':''}>{I&&<I/>}{x as string}</button>)}<small>VIEWS <ChevronDown/></small>{[['My sessions',Activity],['Team activity',Users],['Needs review',ShieldCheck],['Slack requests',Search]].map(([x,I])=><button>{I&&<I/>}{x as string}</button>)}<small>RECENT</small>{sessions.slice(0,3).map(x=><button className="recent"><i/>{x[0]}</button>)}<footer><button><Settings/>Settings</button><button><MoreHorizontal/>More</button></footer></aside><section className="tp-main"><header><h1>{view}</h1><span><button><Search/></button><button>Invite</button><i>E</i></span></header>{view==='Home'?<HomeView query={query} setQuery={setQuery} run={run} setRun={setRun}/>:view==='Sessions'?<Sessions/>:view==='Agents'?<Agents/>:<Reviews/>}</section></main>}
function HomeView({query,setQuery,run,setRun}:{query:string,setQuery:(x:string)=>void,run:boolean,setRun:(x:boolean)=>void}){return <div className="tp-home"><div className="tp-composer"><textarea value={query} onChange={e=>setQuery(e.target.value)} placeholder="What would you like an agent to work on?"/><div><button><GitBranch/> Repositories <ChevronDown/></button><button><Sparkles/> Claude Code: Opus 4.8 <ChevronDown/></button><span/><button onClick={()=>setRun(true)} disabled={!query}><ArrowRight/></button></div></div>{run&&<div className="tp-running"><span><i/>Agent started</span><b>{query}</b><small>Preparing an isolated cloud environment…</small></div>}<Title text="Suggested Agents" count="12"/><div className="tp-templates">{templates.map((x,i)=><article><span>{[<Activity/>,<Workflow/>,<MessageSquare/>][i]}</span><b>{x[0]}</b><p>{x[1]}</p><button onClick={()=>setQuery(x[0])}>Use template</button></article>)}</div><Title text="Active Sessions" count="8"/><div className="tp-session-list">{sessions.slice(0,3).map(x=><Session x={x}/>)}</div></div>}
function Title({text,count}:{text:string,count:string}){return <div className="tp-title"><b>{text}</b><small>{count}</small><a>All <ArrowRight/></a></div>}
function Session({x}:{x:string[]}){return <article className="tp-session"><i className={x[1]==='Needs review'?'review':''}/><span><b>{x[0]}</b><small>Agent · <GitBranch/> {x[2]}</small></span><em>{x[1]}</em><time>{x[3]}</time><MoreHorizontal/></article>}
function Sessions(){return <div className="tp-page"><header><div><h2>Sessions</h2><p>Agent work across your team and repositories.</p></div><button><Plus/>New session</button></header><div className="tp-filters"><button>All sessions <ChevronDown/></button><button>Status <ChevronDown/></button><button>Repository <ChevronDown/></button></div><div className="tp-session-list">{sessions.map(x=><Session x={x}/>)}</div></div>}
function Agents(){return <div className="tp-page"><header><div><h2>Agents</h2><p>Automations that run from events in your stack.</p></div><button><Plus/>New agent</button></header><div className="tp-agent-grid">{templates.concat([['Review every pull request','Reviews code for bugs and security issues on every PR.']]).map((x,i)=><article><span>{[<Activity/>,<Workflow/>,<MessageSquare/>,<GitPullRequest/>][i]}</span><small>ACTIVE</small><h3>{x[0]}</h3><p>{x[1]}</p><footer><b>{i+4} runs this week</b><button><MoreHorizontal/></button></footer></article>)}</div></div>}
function Reviews(){return <div className="tp-page"><header><div><h2>Needs review</h2><p>Completed agent work waiting for a human decision.</p></div></header><div className="tp-review"><aside><span><GitPullRequest/>PR #482</span><h3>Migrate billing cron to the new queue</h3><p>billing-service · opened 8 minutes ago</p><div><b>+330</b><em>-37</em><small>6 files</small></div></aside><main><header><CheckCircle2/><span><b>Ready for review</b><small>All checks passed</small></span></header><pre><code>{`- scheduleJob('*/5 * * * *', bill)
+ await queue.repeat('billing', '5m')
+ logger.info('Billing job queued')`}</code></pre><footer><button>Open pull request <ArrowRight/></button></footer></main></div></div>}
