import Link from'next/link';
import{ArrowRight,BookOpen,CalendarDays,Cloud,Gem,Grid3X3,Sparkles,Table2}from'lucide-react';import styles from'./page.module.css';
const sources=[
 {slug:'monaco',index:'01',name:'Monaco',kind:'Revenue engine',description:'TAM, signals, sequences, meetings, pipeline, and Ask AI.',Icon:Table2,color:'#b9cabe'},
 {slug:'shadcncraft',index:'02',name:'shadcncraft',kind:'Sales system',description:'Seven-route sales app with analytics, campaigns, leads, and deals.',Icon:Grid3X3,color:'#d7c295'},
 {slug:'brutalist-icons',index:'03',name:'Brutalist icons',kind:'Material study',description:'Lucide primitives rendered as one-bit Xerox and cut concrete.',Icon:ArrowRight,color:'#e6e1d5'},
 {slug:'opensourceui',index:'04',name:'OpenSourceUI',kind:'Calendar kit',description:'Five real calendar components in one copy-paste docs shell.',Icon:CalendarDays,color:'#bd4a3c'},
 {slug:'tembo',index:'05',name:'Tembo',kind:'Cloud agents',description:'Cloud agent sessions, automations, and pull-request review.',Icon:Cloud,color:'#477db6'},
 {slug:'profound',index:'06',name:'Profound',kind:'AI marketing',description:'AI Marketer, answer visibility, citations, and prompt analytics.',Icon:Gem,color:'#181818'},
];
export default function Home(){return <main className={styles.page}><nav><Link href="/" className={styles.brand}><i/>INSPIRATION</Link><span>6 source studies · 1 working prototype</span><Link href="/storybook"><BookOpen/>Storybook</Link></nav><section className={styles.hero}><div><span className={styles.label}>DESIGN RESEARCH / PRODUCT PROTOTYPES</span><h1>Real references.<br/><em>Working interfaces.</em></h1><p>Source-faithful marketing recreations and interactive product studies, grounded in live sites, component libraries, and detailed design records.</p></div><aside><small>NEW / INTERNAL TOOL</small><h2>Agentic Sales</h2><p>A command center for account signals, observable agent work, next-best actions, and human approval.</p><Link href="/inspirations/agentic-sales/product">Open prototype <ArrowRight/></Link></aside></section><section className={styles.sectionHead}><div><small>SOURCE LIBRARY</small><h2>Six systems, rebuilt.</h2></div><p>Open the product directly, or inspect the matching marketing language and DESIGN.md provenance.</p></section><section className={styles.grid}>{sources.map(({slug,index,name,kind,description,Icon,color})=><article className={styles.card} key={slug} style={{'--tone':color}as React.CSSProperties}><header><span>{index}</span><Icon/></header><div><small>{kind}</small><h3>{name}</h3><p>{description}</p></div><footer><Link href={`/inspirations/${slug}/marketing`}>Marketing</Link><Link href={`/inspirations/${slug}/product`}>Product <ArrowRight/></Link></footer></article>)}</section><section className={styles.method}><div><small>METHOD</small><h2>Evidence before aesthetics.</h2></div><div><p>Every source includes role-based tokens, type scale, spacing, radii, layout, elevation, component treatment, and do/don't rules.</p><p>Refero is checked first for an exact design record. When none exists, the record is inferred from the live source and marked that way.</p></div></section><footer className={styles.footer}><b><i/>INSPIRATION</b><span>Next.js · Storybook · Tailwind · Radix · Recharts · dnd-kit</span><Link href="/inspirations/agentic-sales/product">Open sales prototype <ArrowRight/></Link></footer></main>}
