'use client';
import React,{useState}from'react';import*as Popover from'@radix-ui/react-popover';import{ArrowUpDown,Building2,Check,ChevronDown,ExternalLink,Filter,Flame,Link2,Plus,Search,Sparkles,Users,Zap}from'lucide-react';
type A={name:string;mark:string;status:'New'|'Prospecting';grade:'A'|'B';heat:'Burning'|'Hot';industries:string[];people:string[];investor:boolean;sales:boolean;reason:string;signals:string[]};
const A:A[]=[
['Judgment Labs','JL','New','A','Burning',['Artificial Intelligence','Developer tools'],['Sam Blond','Malay Desai'],1,1,'Multiple high-intent signals make this account a strong fit right now.',['Raised a growth round in the last 30 days','Opened 4 sales and revenue roles this month','Two warm paths are available']],
['Bluesky Systems','BS','New','A','Burning',['Developer tools','Data'],['Shek Viswanathan','Tom Crane'],1,1,'Strong team growth and visible enterprise motion.',['Announced a new enterprise governance tier','Added a VP Sales and two account executives']],
['Nowadays','NW','New','A','Hot',['Artificial Intelligence'],['Malay Desai'],1,1,'A high-fit AI account with recent buying signals.',['Engineering shared an active CRM migration','Team size is up 24% in six months']],
['Parley','PY','Prospecting','A','Burning',['Artificial Intelligence','Fintech'],['Sam Blond'],1,0,'Active engagement plus clear expansion signals.',['Two stakeholders engaged with outreach','Launched in three new markets this quarter']],
['Backops','BO','New','A','Hot',['Artificial Intelligence','Fintech'],['Shek Viswanathan'],1,1,'Good category match with fresh buyer intent.',['Repeated visits to integration and pricing pages','Recently hired a Head of Revenue Operations']],
['Flowing Health','FH','New','A','Burning',['Artificial Intelligence','Healthcare'],['Tommy Hung'],1,0,'Rapid commercial hiring points to a new sales motion.',['Five new GTM roles appeared this week','Added an enterprise analytics product']],
['Solve Intelligence','SI','New','A','Burning',['Artificial Intelligence','Infrastructure'],['Sam Blond'],1,0,'Exceptional fit and a direct warm path.',['A trusted connection knows the founder','Shipped its enterprise API last week']],
['Juicebox','JB','New','A','Hot',['Artificial Intelligence','Infrastructure'],['Stan Rapp'],1,1,'Strong product fit and a growing enterprise focus.',['Published first named Fortune 500 customer','Reported 3x query volume since January']],
['Delve','DV','New','B','Hot',['Artificial Intelligence','Infrastructure'],['Malay Desai'],0,1,'Good ICP fit, but the timing signals are less recent.',['Security automation matches the target profile','Headcount is up 8% over six months']],
['Sphinx','SX','Prospecting','A','Burning',['Artificial Intelligence','Cybersecurity'],['Sam Blond'],0,1,'Live deal activity and a new sales leader raise priority.',['Three stakeholders opened the workspace','A new CRO joined this month']]
].map(x=>{let[n,m,s,g,h,i,p,v,l,r,z]=x as any;return{name:n,mark:m,status:s,grade:g,heat:h,industries:i,people:p,investor:!!v,sales:!!l,reason:r,signals:z}});
const chip=(text:string,c:string)=><span className={'chip '+c}>{text}</span>;
function Score({a}:{a:A}){return <Popover.Root><Popover.Trigger className="score"><b>{a.grade}</b><i/>🔥 <span>{a.heat}</span></Popover.Trigger><Popover.Portal><Popover.Content className="pop" sideOffset={8} align="start"><div className="pophead"><small>AI SCORE · {a.grade} / {a.heat.toUpperCase()}</small><h3>Why {a.name} is prioritized</h3><p>{a.reason}</p></div><div className="signals">{a.signals.map((s,i)=><div className="signal"><em>{i?<Sparkles/>:<Zap/>}</em><div><b>{s}</b><p>{i?'Verified from company and hiring activity.':'Detected as a recent account signal.'}</p></div></div>)}</div><div className="sources"><small>SOURCES</small><a href="https://example.com" target="_blank"><ExternalLink/>Company announcement</a><a href="https://example.com" target="_blank"><ExternalLink/>Current openings</a><footer><Sparkles/> Generated from live account signals</footer></div></Popover.Content></Popover.Portal></Popover.Root>}
export function AccountsTable(){const[sel,setSel]=useState<string[]>([]);const toggle=(n:string)=>setSel(s=>s.includes(n)?s.filter(x=>x!==n):[...s,n]);return <main><section><header><div className="brand"><span>M</span><b>Accounts</b><small>· 10 companies</small></div><nav><button><Search/>Search</button><button><Filter/>Filter</button><button className="primary"><Plus/>Add account</button></nav></header><div className="scroll"><div className="table"><div className="row th"><div/><div><Building2/>Account<ChevronDown/></div><div><ArrowUpDown/>Status<ChevronDown/></div><div><Flame/>Score<ChevronDown/></div><div><Building2/>Industries</div><div><Users/>Connected to</div><div><Link2/>Common Investor?</div><div><Check/>Sales-led growth?</div></div>{A.map(a=><div className="row"><div><button className={'box '+(sel.includes(a.name)?'on':'')} onClick={()=>toggle(a.name)}>{sel.includes(a.name)&&<Check/>}</button></div><div className="account"><span>{a.mark}</span><b>{a.name}</b></div><div>{chip(a.status,a.status==='New'?'new':'prospecting')}</div><div><Score a={a}/></div><div className="nowrap">{a.industries.map(i=>chip(i,i.includes('Artificial')?'ai':i==='Developer tools'||i==='Fintech'?'dev':'data'))}</div><div className="nowrap">{a.people.map(p=>chip(p,'person'))}</div><div>{chip(a.investor?'Yes':'No',a.investor?'yes':'no')}</div><div>{chip(a.sales?'Yes':'No',a.sales?'yes':'no')}</div></div>)}</div></div><footer className="foot"><span>{sel.length?sel.length+' selected':'Click any score to inspect its reasoning'}</span><span>Last enriched 4 min ago</span></footer></section></main>}
