'use client';
import React,{useMemo,useState}from'react';
import Link from'next/link';
import*as Popover from'@radix-ui/react-popover';
import{Activity,ArrowRight,BarChart3,Bot,Building2,Check,ChevronRight,Flame,GitBranch,GripVertical,MessageSquare,MoreHorizontal,Play,Plus,Search,Send,Sparkles,Users,Zap}from'lucide-react';
import'./monaco-crm.css';
export type MonacoView='accounts'|'pipeline'|'automations'|'activity'|'ask';
const accounts=[['Judgment Labs','AI / Devtools','Burning','A','Prospecting','$84k'],['Bluesky Systems','Data','Burning','A','Qualified','$126k'],['Nowadays','AI','Hot','A','New','$44k'],['Parley','Fintech','Burning','A','Proposal','$98k'],['Backops','AI / Fintech','Hot','A','New','$37k'],['Solve Intelligence','Infrastructure','Burning','A','Negotiation','$158k']];
const deals={Discovery:[['Northstar rollout','$42k','MP'],['Backops workspace','$37k','AL']],Qualified:[['Bluesky governance','$126k','SR'],['Nowadays agents','$44k','MP']],Proposal:[['Parley expansion','$98k','SR']],Negotiation:[['Solve enterprise','$158k','AL']]};
const events=[['Email opened','Parley','Proposal PDF opened by Rebecca Yu','2m'],['Signal detected','Solve Intelligence','Opened 5 enterprise sales roles','14m'],['Call completed','Bluesky Systems','Pricing and security review · 31 min','42m'],['Stage changed','Nowadays','Discovery → Qualified','1h'],['Note added','Judgment Labs','Warm intro confirmed through Benchmark','3h']];
const nav:[MonacoView,string,React.ElementType][]=[['accounts','Accounts',Building2],['pipeline','Pipeline',BarChart3],['automations','Automations',GitBranch],['activity','Activity',Activity],['ask','Ask Monaco',MessageSquare]];
function Shell({view,children}:{view:MonacoView;children:React.ReactNode}){return <main className="mc"><aside><Link href="/" className="mc-logo">M</Link><nav>{nav.map(([id,label,Icon])=><Link key={id} className={view===id?'on':''} href={`/inspirations/monaco/${id}`}><Icon/>{label}</Link>)}</nav><div className="mc-user"><span>EC</span><div><b>Evan's workspace</b><small>Production</small></div></div></aside><section className="mc-work"><header><div><small>MONACO / CRM</small><strong>{nav.find(n=>n[0]===view)?.[1]}</strong></div><div><button><Search/>⌘ K</button><button className="mc-primary"><Plus/>Create</button></div></header>{children}</section></main>}
function Accounts(){const[open,setOpen]=useState<string|null>(null);return <div className="mc-page"><div className="mc-title"><div><h1>Accounts</h1><p>Prioritized from live fit, timing, and relationship signals.</p></div><button><Zap/>Enrich all</button></div><div className="mc-table"><div className="mc-tr head"><span>ACCOUNT</span><span>INDUSTRY</span><span>SCORE</span><span>STAGE</span><span>PIPELINE</span><span/></div>{accounts.map(a=><div className="mc-tr" key={a[0]}><span className="company"><i>{a[0].split(' ').map(x=>x[0]).join('')}</i><b>{a[0]}</b></span><span>{a[1]}</span><span><Popover.Root open={open===a[0]} onOpenChange={v=>setOpen(v?a[0]:null)}><Popover.Trigger className="mc-score"><b>{a[3]}</b><Flame/>{a[2]}</Popover.Trigger><Popover.Portal><Popover.Content className="mc-pop" sideOffset={8}><small>AI SCORE · LIVE</small><h3>Why {a[0]} is prioritized</h3><p>Fresh hiring, product, and engagement signals align with the team's target profile.</p><div><Zap/><span><b>High-intent activity</b><small>Verified in the last 24 hours</small></span></div><div><Users/><span><b>Warm path available</b><small>2 relationship edges found</small></span></div></Popover.Content></Popover.Portal></Popover.Root></span><span><i className="stage">{a[4]}</i></span><span>{a[5]}</span><span><MoreHorizontal/></span></div>)}</div></div>}
function Pipeline(){return <div className="mc-page"><div className="mc-title"><div><h1>Pipeline</h1><p>$587k open · 21 opportunities · 34% weighted</p></div><button><BarChart3/>Forecast</button></div><div className="mc-board">{Object.entries(deals).map(([stage,cards])=><section key={stage}><h3>{stage}<span>{cards.length}</span></h3>{cards.map((d,i)=><article key={d[0]}><div><GripVertical/><b>{d[0]}</b></div><p>{i%2?'Champion engaged · next step booked':'New signal · review due today'}</p><footer><strong>{d[1]}</strong><i>{d[2]}</i></footer></article>)}<button className="mc-add"><Plus/>Add opportunity</button></section>)}</div></div>}
function Automations(){const[on,setOn]=useState([true,true,false]);const flows=[['Route high-intent accounts','Account score becomes Burning','Assign owner · create task','142 runs'],['Advance engaged deals','Meeting completed','Move to Qualified · notify team','86 runs'],['Re-engage stalled pipeline','No activity for 14 days','Draft personalized follow-up','24 runs']];return <div className="mc-page"><div className="mc-title"><div><h1>Automations</h1><p>Build event-driven revenue workflows from live CRM state.</p></div><button className="mc-primary"><Plus/>New automation</button></div><div className="mc-flows">{flows.map((f,i)=><article key={f[0]}><header><button onClick={()=>setOn(x=>x.map((v,j)=>j===i?!v:v))} className={on[i]?'toggle on':'toggle'}><i/></button><div><h3>{f[0]}</h3><p>{f[3]} this month</p></div><MoreHorizontal/></header><div className="flow"><span><Zap/><small>WHEN</small><b>{f[1]}</b></span><ArrowRight/><span><Bot/><small>THEN</small><b>{f[2]}</b></span></div></article>)}</div><section className="mc-builder"><small>VISUAL BUILDER</small><h2>Every workflow is made of replaceable primitives.</h2><div><button><Play/>Trigger</button><ChevronRight/><button><GitBranch/>Condition</button><ChevronRight/><button><Zap/>Action</button></div></section></div>}
function Timeline(){const[filter,setFilter]=useState('All');return <div className="mc-page"><div className="mc-title"><div><h1>Activity</h1><p>One timeline for every account, person, deal, and automation.</p></div><div className="mc-seg">{['All','Signals','Calls','Email'].map(x=><button className={filter===x?'on':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className="mc-timeline">{events.map((e,i)=><article><i>{i===1?<Sparkles/>:i===2?<Users/>:<Activity/>}</i><div><header><b>{e[0]}</b><small>{e[3]}</small></header><a>{e[1]}</a><p>{e[2]}</p></div></article>)}</div></div>}
function Ask(){const[q,setQ]=useState('');const[asked,setAsked]=useState(false);return <div className="mc-ask"><div><Sparkles/><small>ASK MONACO</small><h1>Turn CRM state into an answer.</h1><p>Ask across accounts, opportunities, activity, and live signals. Every answer keeps its sources attached.</p></div><form onSubmit={e=>{e.preventDefault();if(q)setAsked(true)}}><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Which enterprise opportunities need attention this week?"/><button><Send/>Ask</button></form>{!asked?<div className="prompts">{['Show deals at risk','Find warm paths into target accounts','Summarize pipeline changes'].map(x=><button onClick={()=>setQ(x)}>{x}<ChevronRight/></button>)}</div>:<article className="answer"><small><Sparkles/>GENERATED FROM 18 CRM RECORDS</small><h2>Three opportunities need attention.</h2><p><b>Parley</b> has no next step after its proposal opened twice. <b>Solve Intelligence</b> added a new stakeholder but the close plan is stale. <b>Bluesky Systems</b> is waiting on a security response.</p><footer><span>6 activities</span><span>3 opportunities</span><span>Updated now</span></footer></article>}</div>}
export function MonacoCRM({initialView='accounts'}:{initialView?:MonacoView}){return <Shell view={initialView}>{initialView==='accounts'?<Accounts/>:initialView==='pipeline'?<Pipeline/>:initialView==='automations'?<Automations/>:initialView==='activity'?<Timeline/>:<Ask/>}</Shell>}
