'use client';
import React,{useState}from'react';
import Link from'next/link';
import*as Popover from'@radix-ui/react-popover';
import*as Tabs from'@radix-ui/react-tabs';
import{DndContext,DragEndEvent,useDraggable,useDroppable}from'@dnd-kit/core';
import{Bot,Building2,Calendar,Check,ChevronDown,CircleDollarSign,Clock3,Columns3,ExternalLink,Flame,Gift,GripVertical,Lightbulb,Mail,MessageSquare,Mic,MoreHorizontal,Paperclip,Play,Plus,Search,Send,SlidersHorizontal,Sparkles,Trash2,Users,Video,Zap}from'lucide-react';
import'./monaco-crm.css';
export type MonacoView='accounts'|'signals'|'sequences'|'activity'|'pipeline'|'ask';
const nav:[MonacoView,string][]=[['accounts','Build TAM'],['signals','Overlay signals'],['sequences','Execute sequences'],['activity','Capture activity'],['pipeline','Track pipeline'],['ask','Ask Monaco']];
const rows=[
['Judgment Labs','JL','New','Artificial Intelligence','Fintech','Sam Blond','Malay Desai','Yes','Yes','Yes'],['Bluenote','BL','New','Software development','Payment','Shek Viswanathan','Tommy Hung','Yes','Yes','No'],['Nowadays','NW','New','Artificial Intelligence','B2B','Malay Desai','','Yes','Yes','Yes'],['Parley','PA','Prospecting','Artificial Intelligence','Fintech','Sam Blond','','Yes','No','No'],['Backops','BO','New','Artificial Intelligence','Fintech','Shek Viswanathan','','Yes','Yes','Yes'],['Flowline Health','FH','New','Artificial Intelligence','Personal Finance','Tommy Hung','','Yes','No','No'],['Solve Intelligence','SI','New','Artificial Intelligence','Investor','Sam Blond','','Yes','No','No'],['Juicebox','JB','New','Artificial Intelligence','Investor','Stan Rapp','','Yes','Yes','Yes'],['Delve','DE','New','Artificial Intelligence','Investor','Malay Desai','','No','Yes','No'],['Sphinx','SP','Prospecting','Artificial Intelligence','Crypto','Sam Blond','','No','Yes','Yes'],['Casca','CA','New','Artificial Intelligence','Investor','Malay Desai','','No','Yes','Yes']];
function Mark(){return <span className="mk"><i/><i/><i/><i/></span>}
function Shell({view,children}:{view:MonacoView;children:React.ReactNode}){return <main className="monaco"><header className="monaco-bar"><Link href="/" className="brand"><Mark/>MONACO</Link><nav>{nav.map(([id,label],i)=><Link className={view===id?'active':''} href={`/inspirations/monaco/${id}`}><span>{i+1}</span>{label}</Link>)}</nav><div><button><Search/>Search</button><button className="avatar">ES</button></div></header><div className="monaco-body"><aside><b>Revenue engine</b>{nav.map(([id,label])=><Link className={view===id?'active':''} href={`/inspirations/monaco/${id}`}>{label}</Link>)}<small>WORKSPACE</small><a>Leaderboard</a><a>Automations</a><a>Settings</a></aside><section className="surface">{children}</section></div></main>}
function Yes({v}:{v:string}){return <span className={'yes '+(v==='Yes'?'good':'no')}>{v}</span>}
function Score(){return <span className="score"><b>A</b><Flame/>Burning</span>}
function Sources(){return <Popover.Root><Popover.Trigger className="yes good">Yes</Popover.Trigger><Popover.Portal><Popover.Content className="reason" sideOffset={9}><Tabs.Root defaultValue="reason"><Tabs.List><Tabs.Trigger value="reason">Reasoning</Tabs.Trigger><Tabs.Trigger value="sources">Sources</Tabs.Trigger></Tabs.List><Tabs.Content value="reason"><p>Judgment Labs common investors with Monaco include Founders Fund.</p><div className="sourcecards"><article><i>JL</i><small>JudgmentLabs.com</small><b>Judgment Labs Announces Series...</b></article><article><i>Y</i><small>blog.ycombinator.com</small><b>AI Assistant Startups funded...</b></article><article><i>M</i><small>menlovc.com</small><b>The State of Generative AI in...</b></article></div></Tabs.Content><Tabs.Content value="sources"><p>Three current public sources were checked. Open a source to verify the underlying claim.</p></Tabs.Content></Tabs.Root></Popover.Content></Popover.Portal></Popover.Root>}
function Table({signal=false}:{signal?:boolean}){return <div className="account-table"><div className="atr ahead"><span/><span><Building2/>Account</span><span>Status</span><span>Score</span><span>Industries</span><span>Connected to</span><span>Common Investor?</span><span>Sales-led growth?</span><span>YC Company?</span></div>{rows.map((r,i)=><div className={'atr '+(signal&&i!==0?'dim':'')}><span><input type="checkbox"/></span><span className="acct"><i>{r[1]}</i><u>{r[0]}</u></span><span><em className={r[2]==='Prospecting'?'blue':''}>{r[2]}</em></span><span><Score/></span><span><em className="pink">{r[3]}</em> <em className="gold">{r[4]}</em></span><span><em>{r[5]}</em> {r[6]&&<em>{r[6]}</em>}</span><span>{signal&&i===0?<Sources/>:<Yes v={r[7]}/>}</span><span><Yes v={r[8]}/></span><span><Yes v={r[9]}/></span></div>)}</div>}
function Toolbar({title,subtitle}:{title:string;subtitle:string}){return <div className="toolbar"><div><h1>{title}</h1><p>{subtitle}</p></div><div><button><SlidersHorizontal/>View</button><button><Plus/>Add</button></div></div>}
function Accounts(){return <><Toolbar title="Accounts" subtitle="Every account in your TAM, continuously scored and enriched."/><div className="statrow"><article><small>Total addressable market</small><b>12,842</b><span>+426 this month</span></article><article><small>Burning accounts</small><b>184</b><span>42 new signals</span></article><article><small>Warm paths</small><b>73%</b><span>across top 100</span></article><article><small>Pipeline sourced</small><b>$2.4m</b><span>this quarter</span></article></div><Table/></>}
function Signals(){return <><Toolbar title="Signals" subtitle="Prioritize the right companies with explainable, sourced attributes."/><Table signal/></>}
const steps=[['Fundraise gifting','Today, Feb 11'],['Wait 3 business days',''],['Gift reminder',''],['Wait 3 business days',''],['Final message','']];
function Sequences(){const[a,setA]=useState(0);return <div className="sequence"><section className="rail"><div className="seqtitle"><b>Fundraise gifting</b><button><Play/>Live</button></div>{steps.map((s,i)=><button onClick={()=>setA(i)} className={a===i?'on':''}><i>{i%2?i===1||i===3?<Clock3/>:i:<span>{i/2+1}</span>}</i><span><b>{s[0]}</b><small>{s[1]}</small></span></button>)}</section><section className="composer"><header><span><Gift/>Fundraise gifting</span><Trash2/></header><label><span>Recipient:</span><input value="Alex Shan" readOnly/></label><label><span>Subject:</span><input value="Congrats on the fundraise!" readOnly/></label><div className="gift"><span>Gift:</span><div className="bottle"><i/><b>PERSONALISE ME</b><span/></div><h2>Veuve Clicquot<br/>Yellow Label Brut<small>750ml</small></h2></div><label className="message"><span>Message:</span><textarea defaultValue={'Hi Alex - congrats on the recent fundraise!\n\nSending a bottle of Veuve your way as a quick congrats.'}/></label></section></div>}
function Activity(){const[tab,setTab]=useState('notes');return <div className="meeting"><section className="video"><div className="person p1"><span>AS</span><b>Alex Shan</b></div><div className="person p2"><span>SB</span><b>Sam Blond</b></div><div className="callbar"><Mic/><Video/><button>Leave</button></div></section><section className="notes"><Tabs.Root value={tab} onValueChange={setTab}><Tabs.List><Tabs.Trigger value="notes">Meeting Notes</Tabs.Trigger><Tabs.Trigger value="timeline">Timeline</Tabs.Trigger></Tabs.List><Tabs.Content value="notes"><small>MEETING NOTES</small><h2>Virtual Meeting with Alex Shan</h2><p>Great first call with Alex at Judgment Labs. Strong interest in Monaco's agent capabilities for generating demand and increasing conversion rates to grow revenue faster.</p><h4>Key Points</h4><ul><li>Current CRM is Hubspot</li><li>Point solutions are Apollo and Fireflies</li></ul><h4>Budget and Team Size</h4><ul><li>Current budget is $30,000</li><li>Sales team size is 4</li></ul><button><Sparkles/>Create follow-up</button></Tabs.Content><Tabs.Content value="timeline">{['Call started · 10:02','Pricing discussed · 10:18','Next step confirmed · 10:29'].map(x=><p className="event">{x}</p>)}</Tabs.Content></Tabs.Root></section></div>}
const deals=[['Dust','$55,000','DU'],['Judgment Labs','$30,000','JL'],['Vellum AI','$45,000','VA'],['Aperture','$72,000','AP'],['Parley','$38,000','PA']];
function Deal({d,i}:{d:string[],i:number}){const{attributes,listeners,setNodeRef,transform}=useDraggable({id:d[0]});return <button ref={setNodeRef} {...attributes}{...listeners} style={{transform:transform?`translate3d(${transform.x}px,${transform.y}px,0)`:undefined}} className={'deal '+(i===1?'selected':'')}><i>{d[2]}</i><span><b>{d[0]}</b><small>{d[1]}</small></span>{i===1&&<Zap/>}</button>}
function Pipeline(){function end(e:DragEndEvent){}return <div className="pipe"><DndContext onDragEnd={end}><section className="dealcol"><header><b>Evaluation</b><span>5 · $240k</span></header>{deals.map((d,i)=><Deal d={d} i={i}/>)}</section></DndContext><section className="overview"><div className="ovhead"><h1>Judgment Labs</h1><button><MoreHorizontal/></button></div><h2>Overview</h2><h3>Summary</h3><p>Judgment Labs in active evaluation stage; first Monaco demo completed and follow-up sessions scheduled. Slack channel connected and product materials shared; next step is deeper walkthrough with broader stakeholder group. Owner Sam Blond. Expected Close Date: November 30, 2025</p><ul><li><b>October 27, 2025:</b> Monaco &lt;&gt; Judgment Labs follow-up scheduled to go deeper on TAM, sequences, and pipeline.</li><li><b>October 21, 2025:</b> Alex opened pricing and shared it with the buying team.</li></ul><div className="reengage"><Sparkles/><span><b>Re-engage this account</b><small>Alex mentioned hiring two AEs. Draft a note tied to the expansion.</small></span><button>Draft</button></div></section><aside className="leader"><small>REVENUE LEADERBOARD</small>{[['Sam Blond','$482k'],['Amy Liu','$394k'],['Matt Park','$281k']].map((x,i)=><p><i>{i+1}</i><span>{x[0]}</span><b>{x[1]}</b></p>)}</aside></div>}
function Ask(){const[q,setQ]=useState('How could I have done a better job on the Judgment Labs demo?');const[asked,setAsked]=useState(true);return <div className="askstage"><div className="faded"><Table/></div><section className="askbox"><header><span><Mark/>Ask AI</span><div><Lightbulb/><Columns3/><b>×</b></div></header>{asked&&<><div className="question">{q}</div><article><h3>You Lost Control - This Demo Was About You, Not Their Pain</h3><ul><li>You let the intro linger, and waited too long to set agenda or show the product, wasting Alex's attention.</li><li>Demo focused on Monaco's features, not Judgment Labs' pain. Alex mentioned frustration with his existing set of tools and you never asked why.</li><li>Ended without a time confirmed calendar invite sent for the onboarding call. This introduces risk that the opportunity will be delayed and time kills all deals.</li></ul><div className="citations"><button><Paperclip/>Call transcript · 32:14</button><button><ExternalLink/>Judgment Labs</button></div></article></>}<form onSubmit={e=>{e.preventDefault();setAsked(true)}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask follow-up"/><button><Send/></button></form></section></div>}
export function MonacoCRM({initialView='accounts'}:{initialView?:MonacoView}){return <Shell view={initialView}>{initialView==='accounts'?<Accounts/>:initialView==='signals'?<Signals/>:initialView==='sequences'?<Sequences/>:initialView==='activity'?<Activity/>:initialView==='pipeline'?<Pipeline/>:<Ask/>}</Shell>}
